#!/usr/bin/env python3
"""
Aggregate every completed review into a single plan: milestones, phases, todos.

  python3 .loop/plan.py            # rebuild .loop/PLAN.md from .loop/reviews/
  python3 .loop/plan.py --add "<model>" "<text>"   # append a triage note

The plan is generated, never hand-maintained: a ledger that drifts from the
reviews it summarises is worse than none.
"""
import json, os, re, collections, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
REVIEWS = ".loop/reviews"
TRIAGE = ".loop/triage.json"

SEV_ORDER = {"BLOCKER": 0, "MAJOR": 1, "MINOR": 2}

FINDING_RE = re.compile(r"^#{2,4}\s*(\d+)[.)\s]+(.+?)\s*$", re.M)
SEV_RE = re.compile(r"\*\*Severity:?\*\*:?\s*(BLOCKER|MAJOR|MINOR)", re.I)
EVID_RE = re.compile(r"\*\*Evidence:?\*\*:?\s*(.+?)(?=\n\*\*|\n##|\Z)", re.S)
WHY_RE = re.compile(r"\*\*Why it matters:?\*\*:?\s*(.+?)(?=\n\*\*|\n##|\Z)", re.S)
FIX_RE = re.compile(r"\*\*Suggested fix:?\*\*:?\s*(.+?)(?=\n\*\*|\n##|\Z)", re.S)


def load_triage():
    if os.path.exists(TRIAGE):
        return json.load(open(TRIAGE))
    return {}


def save_triage(t):
    json.dump(t, open(TRIAGE, "w"), indent=1)


def collect():
    findings = []
    if not os.path.isdir(REVIEWS):
        return findings

    for fn in sorted(os.listdir(REVIEWS)):
        if not fn.endswith(".md"):
            continue
        text = open(os.path.join(REVIEWS, fn), encoding="utf-8", errors="replace").read()
        model = fn[3:].rsplit(".md", 1)[0].replace("__", "/")
        heads = list(FINDING_RE.finditer(text))
        for i, m in enumerate(heads):
            seg = text[m.end(): heads[i + 1].start() if i + 1 < len(heads) else len(text)]
            sev = SEV_RE.search(seg)
            if not sev:
                continue  # a preamble heading, not a finding
            findings.append({
                "model": model,
                "n": int(m.group(1)),
                "title": m.group(2).strip(),
                "severity": sev.group(1).upper(),
                "evidence": (EVID_RE.search(seg).group(1).strip() if EVID_RE.search(seg) else "")[:400],
                "why": (WHY_RE.search(seg).group(1).strip() if WHY_RE.search(seg) else "")[:400],
                "fix": (FIX_RE.search(seg).group(1).strip() if FIX_RE.search(seg) else "")[:600],
            })
    return findings


def main():
    args = sys.argv[1:]
    triage = load_triage()

    if args and args[0] == "--add":
        model = args[1]
        note = args[2]
        notes = triage.setdefault(model, [])

        # `TriageStatusMarkerTest` requires the FIRST note of every `audit/` key to
        # open with a status marker. This command has been the eighth way to break
        # that rule across 126 iterations — every one of them this exact line,
        # because `--add` takes free text and nothing here shaped it. Rather than
        # rely on remembering, an audit key created with no marker is given one.
        #
        # `#OPEN` is the default because that is what a one-line `--add` almost
        # always records: something observed and not yet fixed. If the note is
        # explicitly about a fix that landed, edit the marker — this only stops an
        # unmarked entry, it does not guess your status for you.
        if model.startswith("audit/") and notes and not notes[0].startswith(
            ("#RESOLVED", "#OPEN", "#CLOSED", "#RETRACTED")
        ):
            notes.insert(0, "#OPEN — status not stated; set it when the work closes.")

        notes.append(note)
        save_triage(triage)
        print(f"triaged note for {model}")
        return

    findings = collect()
    by_sev = collections.defaultdict(list)
    for f in findings:
        by_sev[f["severity"]].append(f)

    models = sorted({f["model"] for f in findings})
    resolved = sum(len(v) for v in triage.values())

    L = []
    A = L.append
    A("# Review loop — accumulated plan\n")
    A(f"_Generated by `.loop/plan.py`. Do not hand-edit; rerun after each review._\n")
    A(f"**Reviewers heard:** {len(models)} · **findings raised:** {len(findings)} · **findings triaged:** {resolved}\n")

    A("\n## Milestone status\n")
    A("| Milestone | State |")
    A("|---|---|")
    A("| M1 — review harness + vision packet | ✅ done |")
    A("| M2 — first review round triaged and fixed | ✅ done |")
    A("| M3 — every roster model asked | 🔄 in progress |")
    A("| M4 — plan from accumulated feedback executed | ⬜ not started |")

    A("\n## Reviewers\n")
    A("| # | Model | Findings | Triaged |")
    A("|---|---|---|---|")
    for m in models:
        n = sum(1 for f in findings if f["model"] == m)
        t = len(triage.get(m, []))
        A(f"| | `{m}` | {n} | {t} |")

    for sev in ("BLOCKER", "MAJOR", "MINOR"):
        items = by_sev.get(sev, [])
        if not items:
            continue
        A(f"\n## {sev} ({len(items)})\n")
        for f in sorted(items, key=lambda x: (x["model"], x["n"])):
            A(f"### [{f['model'].split('/')[-1]}] {f['title']}\n")
            A(f"- **Evidence:** `{f['evidence'][:220]}`")
            A(f"- **Why:** {f['why'][:220]}")
            A(f"- **Fix:** {f['fix'][:260]}")
            A("")

    open(".loop/PLAN.md", "w", encoding="utf-8").write("\n".join(L))
    print(f"plan: {len(findings)} findings from {len(models)} reviewers -> .loop/PLAN.md")


if __name__ == "__main__":
    main()
