<?php

declare(strict_types=1);

namespace LangChain\LanguageModels\Chat\Anthropic;

/**
 * Static capability profiles for Anthropic models.
 *
 * Port of `profiles.ts` from `@langchain/anthropic` (generated upstream; the
 * table is copied verbatim, camelCase keys included, so a profile compares equal
 * to the JS `ModelProfile`).
 */
final class Profiles
{
    /** @var array<string, array<string, int|bool>> */
    public const PROFILES = [
        'claude-sonnet-4-6' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-haiku-4-5' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-6' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-fable-5' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-fable-5-1' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => true,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-8' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-1' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 32000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-sonnet-4-5' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-sonnet-4-5-20250929' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-5-20251101' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-haiku-4-5-20251001' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-7' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-5' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 64000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-sonnet-5' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-5' => [
            'maxInputTokens' => 1000000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 128000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
        'claude-opus-4-1-20250805' => [
            'maxInputTokens' => 200000,
            'imageInputs' => true,
            'audioInputs' => false,
            'pdfInputs' => true,
            'videoInputs' => false,
            'maxOutputTokens' => 32000,
            'reasoningOutput' => true,
            'imageOutputs' => false,
            'audioOutputs' => false,
            'videoOutputs' => false,
            'toolCalling' => true,
            'structuredOutput' => false,
            'imageUrlInputs' => true,
            'pdfToolMessage' => true,
            'imageToolMessage' => true,
        ],
    ];

    private function __construct()
    {
    }

    /**
     * Every known profile, keyed by model name.
     *
     * @return array<string, array<string, int|bool>>
     */
    public static function all(): array
    {
        return self::PROFILES;
    }

    /**
     * The profile for a model, or `[]` when the model is unknown
     * (upstream: `PROFILES[this.model] ?? {}`).
     *
     * @return array<string, int|bool>
     */
    public static function for(string $model): array
    {
        return self::PROFILES[$model] ?? [];
    }
}
