<?php

declare(strict_types=1);

namespace LangChain\LanguageModels\Chat\OpenAI\Converters;

use LangChain\Messages\BaseMessage;
use LangChain\Messages\ChatMessage;
use LangChain\Utils\Notice;

/**
 * Small helpers the Responses converters share.
 *
 * Port of the parts of `utils/misc.ts` from `@langchain/openai` that the input
 * side of `converters/responses.ts` calls: prompt-cache breakpoints, the
 * reasoning-model test, filename lookup and the message-to-role map.
 *
 * `console.warn` is recorded with {@see Notice::record()}: an `E_USER_WARNING`
 * would fail any suite that runs with `failOnWarning`, for a condition upstream
 * only logs.
 */
final class Misc
{
    public const LC_AUTOGENERATED_FILENAME = 'LC_AUTOGENERATED';

    private function __construct()
    {
    }

    /**
     * Copy a `prompt_cache_breakpoint` from a source block onto a target part.
     *
     * The key is checked with `array_key_exists`, not `isset`: upstream tests
     * `"prompt_cache_breakpoint" in source`, and an explicit `null` is a real
     * value there (it means "no breakpoint here", and is forwarded as such).
     *
     * @param array<string, mixed> $source
     * @param array<string, mixed> $target
     *
     * @return array<string, mixed>
     */
    public static function applyPromptCacheBreakpoint(array $source, array $target): array
    {
        if (array_key_exists('prompt_cache_breakpoint', $source)) {
            $target['prompt_cache_breakpoint'] = $source['prompt_cache_breakpoint'];

            return $target;
        }

        if (self::hasExtrasPromptCacheBreakpoint($source)) {
            /** @var array<string, mixed> $extras */
            $extras = $source['extras'];
            $target['prompt_cache_breakpoint'] = $extras['prompt_cache_breakpoint'];
        }

        return $target;
    }

    /**
     * @param array<string, mixed> $block
     */
    public static function hasExtrasPromptCacheBreakpoint(array $block): bool
    {
        return is_array($block['extras'] ?? null)
            && array_key_exists('prompt_cache_breakpoint', $block['extras']);
    }

    public static function isReasoningModel(?string $model): bool
    {
        if ($model === null || $model === '') {
            return false;
        }

        if (preg_match('/^o\d/', $model) === 1) {
            return true;
        }

        if (str_starts_with($model, 'gpt-5') && !str_starts_with($model, 'gpt-5-chat')) {
            return true;
        }

        return str_starts_with($model, 'gpt-6') && !str_starts_with($model, 'gpt-6-chat');
    }

    /**
     * `metadata.filename ?? metadata.name ?? metadata.title`.
     *
     * @param array<string, mixed> $block
     */
    public static function getFilenameFromMetadata(array $block): ?string
    {
        $metadata = $block['metadata'] ?? null;
        if (!is_array($metadata)) {
            return null;
        }

        foreach (['filename', 'name', 'title'] as $key) {
            if (isset($metadata[$key])) {
                return is_string($metadata[$key]) ? $metadata[$key] : (string) json_encode($metadata[$key]);
            }
        }

        return null;
    }

    /**
     * The filename, or a placeholder (with a warning) when the block has none.
     *
     * @param array<string, mixed> $block
     */
    public static function getRequiredFilenameFromMetadata(array $block): string
    {
        $filename = self::getFilenameFromMetadata($block);

        if ($filename === null || $filename === '') {
            self::warn(
                'OpenAI may require a filename for file uploads. Specify a filename in the content block '
                . "metadata, e.g.: ['type' => 'file', 'mimeType' => '...', 'data' => '...', "
                . "'metadata' => ['filename' => 'my-file.pdf']]. Using placeholder filename 'LC_AUTOGENERATED'."
            );

            return self::LC_AUTOGENERATED_FILENAME;
        }

        return $filename;
    }

    /**
     * The OpenAI role for a LangChain message.
     *
     * @throws \InvalidArgumentException for a message type with no role.
     */
    public static function messageToOpenAIRole(BaseMessage $message): string
    {
        $type = $message->getType();

        if ($message instanceof ChatMessage) {
            if (!in_array($type, ['system', 'developer', 'assistant', 'user', 'function', 'tool'], true)) {
                self::warn('Unknown message role: ' . $type);
            }

            return $type;
        }

        return match ($type) {
            'system' => 'system',
            'ai' => 'assistant',
            'human' => 'user',
            'function' => 'function',
            'tool' => 'tool',
            default => throw new \InvalidArgumentException('Unknown message type: ' . $type),
        };
    }

    public static function warn(string $message): void
    {
        Notice::record($message);
    }

    /**
     * JS truthiness for the values these converters test: null, false, 0,
     * the empty string and an empty array are all falsy.
     */
    public static function truthy(mixed $value): bool
    {
        return !($value === null || $value === false || $value === '' || $value === 0 || $value === 0.0 || $value === []);
    }
}
