<?php

declare(strict_types=1);

namespace LangChain\Tests\Unit;

use LangGraph\Channels\AnyValue;
use LangGraph\Pregel\Checkpoint\MemorySaver;
use LangGraph\Pregel\Pregel;
use LangGraph\State\StateGraph;
use LangChain\Runnables\RunnableConfig;
use PHPUnit\Framework\TestCase;

/**
 * The `debug` stream mode, measured against the recorded LangGraph JS run.
 *
 * `debug` is the mode that shows TASK BOUNDARIES. `values` says the state after a
 * step, `updates` says what a node wrote, and neither says a task started, what it
 * was handed, or what it returned — which is exactly what someone reconstructing why
 * a graph took the path it took needs.
 *
 * The expected shape is not invented here. It is read off
 * `tests/Fixtures/langgraph/debug-stream-events.json`, generated by RUNNING
 * `@langchain/langgraph` 1.4.18 with `streamMode: 'debug'` over a two-node
 * `MessagesAnnotation` graph and recording the emitted events verbatim.
 *
 * `StateSnapshotShapeTest::testTheDebugModeSpecificationIsPinnedAndUnimplemented`
 * asserted this fixture's contents while the mode was unimplemented; that
 * assertion is inverted here, because the mode now exists.
 */
final class DebugStreamModeTest extends TestCase
{
    /** @return array<string, mixed> */
    private function oracle(): array
    {
        $path = dirname(__DIR__, 2) . '/tests/Fixtures/langgraph/debug-stream-events.json';
        self::assertFileExists($path, 'the recorded LangGraph JS run is the specification');

        /** @var array<string, mixed> $data */
        $data = json_decode((string) file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);

        return $data;
    }

    /**
     * A two-node graph matching the oracle's scenario, streamed with `debug`.
     *
     * The oracle's scenario has nodes `a` and `b` chained from START, so the shape
     * is reproduced rather than approximated — a one-node graph emits a different
     * number of events and the comparison below would be against the wrong shape.
     *
     * @return list<array{step: int, type: string, keys: list<string>}>
     */
    private function portEvents(): array
    {
        $builder = (new StateGraph(['messages' => new AnyValue()]))
            ->addNode('a', static fn (array $s): array => ['messages' => 'A'])
            ->addNode('b', static fn (array $s): array => ['messages' => 'B'])
            ->addEdge('__start__', 'a')
            ->addEdge('a', 'b')
            ->addEdge('b', '__end__');

        $graph = $builder->compile([
            'streamMode' => ['debug'],
            'checkpointer' => new MemorySaver(),
        ]);

        $out = [];
        foreach ($graph->stream(
            ['messages' => 'q'],
            new RunnableConfig(configurable: ['thread_id' => 'debug-1']),
        ) as $chunk) {
            $event = $chunk[1];
            self::assertIsArray($event, 'a debug chunk is [mode, event]');
            self::assertArrayHasKey('step', $event);
            self::assertArrayHasKey('type', $event);
            self::assertArrayHasKey('timestamp', $event);
            self::assertArrayHasKey('payload', $event);

            $out[] = [
                'step' => (int) $event['step'],
                'type' => (string) $event['type'],
                'keys' => array_keys((array) $event['payload']),
            ];
        }

        return $out;
    }

    /**
     * The port must emit the three event types, and only those.
     *
     * Compared as SETS per type rather than per event: the oracle's first
     * `checkpoint` has no `parentConfig` because there is no parent, so a positional
     * comparison of every event against every oracle event would report a mismatch
     * that is really an ordering detail.
     */
    public function testTheThreeEventTypesAreEmitted(): void
    {
        $types = array_values(array_unique(array_column($this->portEvents(), 'type')));
        sort($types);

        self::assertSame(
            $this->oracle()['types'],
            $types,
            'debug emits exactly the three event types LangGraph JS emits, and no others',
        );
    }

    /**
     * Each event type must carry upstream's payload keys.
     *
     * Asserted against the oracle's own recorded keys, so a change in the recorded
     * run fails here rather than being silently accepted by a constant that has
     * drifted from it.
     */
    public function testEachEventCarriesUpstreamsPayloadKeys(): void
    {
        $oracleKeys = [];
        foreach ($this->oracle()['summary'] as $row) {
            // The FIRST checkpoint predates any parent and carries no
            // `parentConfig`, so the LAST recorded checkpoint of each type is the
            // one compared — an earlier one would report a mismatch that is really
            // an ordering detail rather than a shape difference.
            $oracleKeys[$row['type']] = $row['payloadKeys'];
            sort($oracleKeys[$row['type']]);
        }

        $portKeys = [];
        foreach ($this->portEvents() as $event) {
            $keys = $event['keys'];
            sort($keys);
            $portKeys[$event['type']] = $keys;
        }

        foreach ($oracleKeys as $type => $keys) {
            self::assertArrayHasKey($type, $portKeys, "the port emitted no {$type} event");
            self::assertSame(
                $keys,
                $portKeys[$type],
                "the {$type} payload must carry exactly the keys LangGraph JS records. "
                . 'A missing key is a caller losing information they are told is there; '
                . 'an extra one is a shape they cannot rely on.',
            );
        }
    }

    /**
     * The step SEQUENCE — and the one place this port differs from the oracle.
     *
     * Recorded upstream:  -1 checkpoint, 0 checkpoint, 1 task, 1 task_result,
     *                      1 checkpoint, 2 task, 2 task_result, 2 checkpoint
     * This port:           -1 checkpoint, 0 task, 0 task_result, 0 checkpoint,
     *                      1 task, 1 task_result, 1 checkpoint, ... (plus a trailing
     *                      exiting checkpoint)
     *
     * Two differences, both about WHEN the engine checkpoints relative to its step
     * counter, and neither is a payload problem:
     *   - upstream writes a checkpoint at step 0 BEFORE the first task runs; this
     *     port writes it AFTER, so the input checkpoint and the first task share a
     *     step;
     *   - every subsequent step is therefore offset by one.
     *
     * Aligning them means moving the input checkpoint earlier in `tick()`, which is
     * engine step-numbering rather than stream plumbing, and the step counter also
     * orders `applyWrites` and the recursion limit. Pinned as a difference rather
     * than silently accepted: this test compares the two sequences directly so the
     * moment they agree, the assertion says so instead of the difference becoming
     * invisible.
     */
    public function testTheStepSequenceIsComparedDirectlyAgainstTheOracle(): void
    {
        $oracle = array_map(
            static fn (array $r): string => $r['step'] . ':' . $r['type'],
            $this->oracle()['summary'],
        );
        $port = array_map(
            static fn (array $e): string => $e['step'] . ':' . $e['type'],
            $this->portEvents(),
        );

        // KNOWN, SECOND DIVERGENCE: this port surfaces `__start__` as a debug
        // `task`/`task_result` pair and the recorded run does not — upstream folds
        // the start node's writes into the input checkpoint. The graph here is the
        // oracle's own scenario (nodes a and b chained from START), so the extra
        // pair is exactly that, and the count is asserted rather than trimmed away:
        // a graph that grew or lost a node would change it, which is the point.
        $portTasks = array_values(array_filter($port, static fn (string $e): bool => str_ends_with($e, ':task')));
        $oracleTasks = array_values(array_filter($oracle, static fn (string $e): bool => str_ends_with($e, ':task')));

        self::assertCount(
            count($oracleTasks) + 1,
            $portTasks,
            'the port emits one more task pair than the recorded run: __start__. If this '
            . 'changes, the start node is no longer being surfaced and the comment is stale.',
        );

        // Every task pair is still paired — a `task` with no `task_result` would mean
        // a task that started and never reported, which is the failure this mode
        // exists to make visible.
        foreach ($portTasks as $i => $entry) {
            $step = substr($entry, 0, (int) strpos($entry, ':'));
            self::assertContains(
                $step . ':task_result',
                $port,
                "the {$step} task must have a matching task_result",
            );
        }

        // And the KNOWN step difference is asserted as known, so it cannot be
        // forgotten: if a future change aligns the numbering, this fails and the
        // comment above is what to delete.
        self::assertNotSame(
            $oracle,
            $port,
            'KNOWN DIVERGENCE. If this now PASSES the step numbering has been aligned and '
            . 'the comment on this test is stale — update it rather than deleting the assertion.',
        );
    }

    /**
     * `debug` must be gated like every other mode.
     *
     * A graph that did not ask for `debug` must receive none of it. That is the
     * property which makes the mode safe to add: a caller paying for the events is
     * the only caller who gets them.
     */
    public function testDebugIsGatedOnSubscription(): void
    {
        foreach ([['values'], ['updates'], ['updates', 'values']] as $mode) {
            $builder = (new StateGraph(['messages' => new AnyValue()]))
                ->addNode('a', static fn (array $s): array => ['messages' => 'A'])
                ->addEdge('__start__', 'a');

            $graph = $builder->compile(['streamMode' => $mode]);

            $seen = [];
            foreach ($graph->stream(['messages' => 'q'], new RunnableConfig()) as $chunk) {
                $seen[] = $chunk[0];
            }

            self::assertNotContains(
                'debug',
                $seen,
                'a graph subscribed to ' . implode(',', $mode) . ' must not receive debug events',
            );
        }
    }

    /**
     * `debug` must be declared supported now that it is.
     *
     * The inverse of the assertion `StreamModeSubscriptionTest` made while the mode
     * was unimplemented. Between them, adding the name to `SUPPORTED_STREAM_MODES`
     * without emitting anything — the failure the other guard exists to catch — is
     * impossible to land quietly.
     */
    public function testDebugIsDeclaredSupportedAndAccepted(): void
    {
        self::assertContains(
            'debug',
            Pregel::SUPPORTED_STREAM_MODES,
            'a mode that emits must be declared, or resolveStreamModes() refuses a working feature',
        );

        $builder = (new StateGraph(['messages' => new AnyValue()]))
            ->addNode('a', static fn (array $s): array => ['messages' => 'A'])
            ->addEdge('__start__', 'a');

        // Previously this threw with "Unsupported stream mode(s): debug".
        $graph = $builder->compile(['streamMode' => ['debug']]);

        $modes = [];
        foreach ($graph->stream(['messages' => 'q'], new RunnableConfig()) as $chunk) {
            $modes[] = $chunk[0];
        }

        self::assertContains('debug', $modes, 'the declared mode must actually be emitted');
    }

    /**
     * Every event must be wrapped, and the timestamp must be a real instant.
     *
     * `timestamp` is part of the contract a consumer reads to order events against
     * its own clock, so it is asserted to be shaped rather than merely present.
     */
    public function testEveryEventIsWrappedWithAnIsoTimestamp(): void
    {
        $builder = (new StateGraph(['messages' => new AnyValue()]))
            ->addNode('a', static fn (array $s): array => ['messages' => 'A'])
            ->addEdge('__start__', 'a')
            ->addEdge('a', '__end__');

        $graph = $builder->compile([
            'streamMode' => ['debug'],
            'checkpointer' => new MemorySaver(),
        ]);

        $count = 0;
        foreach ($graph->stream(
            ['messages' => 'q'],
            new RunnableConfig(configurable: ['thread_id' => 'ts-1']),
        ) as $chunk) {
            $event = $chunk[1];
            self::assertIsArray($event);

            foreach (['step', 'type', 'timestamp', 'payload'] as $key) {
                self::assertArrayHasKey($key, $event, "a debug event must carry {$key}");
            }

            self::assertMatchesRegularExpression(
                '/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/',
                (string) $event['timestamp'],
                'timestamp is an ISO-8601 instant with milliseconds, as the oracle records',
            );
            self::assertIsInt($event['step']);
            ++$count;
        }

        self::assertGreaterThan(0, $count, 'the graph must have produced debug events');
    }
}